id: PF5E4F9B2
initial_creation_type: input
source_metadata:
  title: Saving Lives Series
  language: pt
  description: 'The following texts are currently available as part of our Saving
    Lives series:'
  volume:
    32d032341c214aa698ccb696b243eb35:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    af4e868cdbde4c21a4068212ceb701fa:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Practices
    b17a69ade1ad415d9ef2adb4cf811717:
      title: 'Increasing Life and Vitality: A Practice for Freeing Lives'
      parent: Practices
    6049a6852de34150a3bcc0b1a4fc1d1e:
      title: 'A River Filled with the Amṛta of Love: A Liturgy for Saving and Releasing
        the Lives of Animals'
      parent: Practices
    d978a01a8a31470dad2dc3d5e900bd60:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Practices
    3c808a0a7ebd446f87cac353775549f9:
      title: The Benefits of Saving Lives
      parent: Commentaries
created_at: '2022-03-01T05:42:44.273632'
last_modified_at: '2022-03-01T05:42:44.273634'
